# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: waybar-niri-windows

builds:
  - env: [CGO_ENABLED=1]
    dir: './lib'
    buildmode: c-shared
    flags: [-trimpath]
    ldflags: [-s -w]
    goos: [linux]
    goarch: [amd64]
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - formats: binary
    name_template: '{{ .ProjectName }}'

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^refactor:'
      - '^style:'
      - '^test:'
